#!/bin/sh
#
# This file is part of openmediavault-subversion.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Marcel Beck <marcel.beck@mbeck.org>
# @copyright Copyright (c) 2012 Marcel Beck
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# The program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_SUBVERSION_AUTHZ=${OMV_SUBVERSION_AUTHZ:-"/etc/subversion/authz"}
OMV_SUBVERSION_CONFIG=${OMV_SUBVERSION_CONFIG:-"/etc/apache2/conf.d/omv-svn"}

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then

    [ -f ${OMV_SUBVERSION_CONFIG} ] && /bin/rm -f ${OMV_SUBVERSION_CONFIG}

    # Clean up after authz_external.. it doesn't disable itself
    # on uninstallation. We have no choice but to disable it on our
    # uninstallation. Otherwise OMV may fail to start apache2 on
    # the next reboot / restart
    [ -f /etc/apache2/mods-enabled/authnz_external.load ] && [ ! -f /etc/apache2/mods-available/authnz_external.load ] && a2dismod authnz_external

    if [ "$1" = "purge" ]; then

        [ -f ${OMV_SUBVERSION_AUTHZ} ] && /bin/rm -f ${OMV_SUBVERSION_AUTHZ}

        omv_config_delete "//services/subversion"

    fi
fi

exit 0
